@startuml

json Buses {
    "_id": "ObjectId('67...da0')",
    "departureTime": "ISODate('2025-03-24T13:00:00.000Z')",
    "departureLocation": "Hồ Chí Minh",
    "timeType": "NIGHT",
    "arrivalTime": "ISODate('2025-03-24T21:00:00.000Z')",
    "arrivalLocation": "Khánh Hòa",
    "fare": 350000,
    "boardingPoints": ["Bến Xe An Sương"],
    "droppingPoints": ["Bến Xe Cam Ranh"],
    "busType": "GHẾ",
    "status": "STILL_AVAILABLE",
    "seats": [
        {
            "seatNumber": "A1",
            "isBooked": false
        },
        {
            "seatNumber": "A2",
            "isBooked": false
        }
    ]
}


json Custommers {
    "_id":"ObjectId('67...6d5')",
    "name": "Long Huynh",
    "gender": ["MALE","FEMALE"],
    "email": "longhuynhdev@gmail.com",
    "phone": "0888703040",
    "password": "hashed_password",
    "role": ["USER","ADMIN"]

}


@enduml
